package io.casehub.clinical.api;

public enum CascadeStepType {
    AE_REPORTED,
    SLA_ASSIGNED,
    ESCALATION_CASE_STARTED,
    AGENT_SELECTED,
    AGENT_REASONING,
    AGENT_RESULT,
    GATE_OPENED,
    GATE_RESOLVED,
    SAFETY_OFFICER_NOTIFIED,
    REGULATORY_SUBMISSION_STARTED,
    LEDGER_SEALED
}
